include: package:very_good_analysis/analysis_options.3.0.0.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

linter:
  rules:
    public_member_api_docs: false
    avoid_print: false
    prefer_single_quotes: true
    lines_longer_than_80_chars: false

  